services:

  api-gateway-ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - JWT_SECRET=supersecreto # eyJhbGciOiJIUzI1NiJ9.e30.DXxIeFW2q8YxQCCDJoI1B0E9QaAAzeVVhDGwjbXFJgo
      - ORDERS_MS_URL=http://orders-ms:3000
      - PRODUCTS_MS_URL=http://products-ms:3001
      - PAYMENTS_MS_URL=http://payments-ms:3002
    networks:
      - pickhealthy-net

volumes:
  postgres_data:

networks:
  pickhealthy-net:
    external: true

# Para reiniciar el volumen de postgres
# docker-compose down
# docker volume rm orders-ms_postgres_data
# docker-compose up --build